# Extension metadata configuration for DuckDB Extensions Analysis
# This file defines special handling rules for extensions that don't follow standard patterns

[core_extensions]

# Extensions with dedicated source directories in the main DuckDB repository
# Note: Most core extensions now have external repositories (see external_repositories section)
[core_extensions.with_source_directories]
autocomplete = { path = "extension/autocomplete" }
icu = { path = "extension/icu" }
jemalloc = { path = "extension/jemalloc" }
json = { path = "extension/json" }
parquet = { path = "extension/parquet" }
tpcds = { path = "extension/tpcds" }
tpch = { path = "extension/tpch" }

# Extensions with external repositories (not in main DuckDB repo)
[core_extensions.external_repositories]
ui = { repository = "duckdb/duckdb-ui", description = "Browser-based user interface for DuckDB" }
avro = { repository = "duckdb/duckdb-avro", description = "Apache Avro format support" }
aws = { repository = "duckdb/duckdb-aws", description = "AWS S3 integration" }
azure = { repository = "duckdb/duckdb-azure", description = "Azure Blob Storage integration" }
delta = { repository = "duckdb/duckdb-delta", description = "Delta Lake format support" }
encodings = { repository = "duckdb/duckdb-encodings", description = "Character encoding support" }
excel = { repository = "duckdb/duckdb-excel", description = "Excel file format support" }
fts = { repository = "duckdb/duckdb-fts", description = "Full-text search functionality" }
httpfs = { repository = "duckdb/duckdb-httpfs", description = "HTTP/S3 filesystem support" }
iceberg = { repository = "duckdb/duckdb-iceberg", description = "Apache Iceberg format support" }
inet = { repository = "duckdb/duckdb-inet", description = "Internet address data types" }
mysql = { repository = "duckdb/duckdb-mysql", description = "MySQL database connectivity" }
postgres = { repository = "duckdb/duckdb-postgres", description = "PostgreSQL database connectivity" }
spatial = { repository = "duckdb/duckdb-spatial", description = "Geospatial data types and functions" }
sqlite = { repository = "duckdb/duckdb-sqlite", description = "SQLite database connectivity" }
vss = { repository = "duckdb/duckdb-vss", description = "Vector similarity search" }

# Manual overrides for extensions that should point to specific directories in the main DuckDB repo
[core_extensions.repository_overrides]
# These extensions don't have separate repositories and should point to specific directories
autocomplete = "https://github.com/duckdb/duckdb/tree/main/extension/autocomplete"
icu = "https://github.com/duckdb/duckdb/tree/main/extension/icu"
jemalloc = "https://github.com/duckdb/duckdb/tree/main/extension/jemalloc"
json = "https://github.com/duckdb/duckdb/tree/main/extension/json"
parquet = "https://github.com/duckdb/duckdb/tree/main/extension/parquet"
tpcds = "https://github.com/duckdb/duckdb/tree/main/extension/tpcds"
tpch = "https://github.com/duckdb/duckdb/tree/main/extension/tpch"
ducklake = "https://github.com/duckdb/ducklake"

# Extensions integrated into core DuckDB without dedicated directories
[core_extensions.integrated_core]
ducklake = { description = "Delta Lake support via DuckLake (different from delta extension)" }

# Special URL patterns for core extensions documentation
[core_extensions.special_urls]
json = "https://duckdb.org/docs/stable/data/json/overview.html"
parquet = "https://duckdb.org/docs/stable/data/parquet/overview.html"

# URL patterns for different extension documentation structures
[url_patterns]
standard = "https://duckdb.org/docs/stable/core_extensions/{name}.html"
overview_pattern = "https://duckdb.org/docs/stable/core_extensions/{name}/overview.html"

# Extensions that use the overview pattern
overview_extensions = ["httpfs", "iceberg", "spatial"]

# Community extension repositories with special handling
[community_extensions]

# Extensions that might need special GitHub API handling
[community_extensions.special_repos]
# Add any community extensions that need special handling here